services:
  streamlit:
    build: .
    ports:
      - "8501:8501"

    develop:
      watch:
        - action: sync
          path: .
          target: /interactive_study
          ignore:
            - .venv/
            - .pytest_cache
        - action: rebuild
          path: ./pyproject.toml
