[project]
name = "study-is-interactive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "streamlit>=1.44.1",
    "sympy>=1.13.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
