[project]
name = "study-is-interactive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "streamlit>=1.44.1",
]

[dependency-groups]
dev = [
    "rust>=1.3.1",
]
